services:
  - type: web
    name: hospital-management-system
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: DB_HOST
        value: gateway01.ap-southeast-1.prod.aws.tidbcloud.com
      - key: DB_PORT
        value: 4000
      - key: DB_NAME
        value: hospital_management_system
      - key: DB_USER
        value: 2xpFsLgSjyJvLBn.root
      - key: DB_PASSWORD
        value: kcBO9ccD8HWq7bbf
      - key: DB_SSL
        value: true
      - key: DB_SSL_MODE
        value: REQUIRED
